# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
let
  bootUUID = "0F6E-A215";
  poolUUID = "8f9e86bc-dfee-4d4a-bc6a-00127d43ce3e";
in
{
  imports = let 
    pkgs = import <nixpkgs> { config.packageOverrides = import ../pkgs; };
    systemd-zfs-generator = pkgs.fetchgit {
      url = "https://github.com/edef1c/systemd-zfs-generator";
      rev = "4dbf1bc609b6f05b82ae0cbac734bf4bac9bdedb";
      sha256 = "087vz3y96mypg7a41fm1zd8xkxkl9zbcm2b3lq9jyzjnd82g059c";
    };
  in builtins.map (drv: drv.outPath) [ systemd-zfs-generator ];

  networking.hostId = "dd405a3f";

  fileSystems."/" =
    { device = "storage/root/nixos";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "storage/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/${bootUUID}";
      fsType = "vfat";
    };

  swapDevices = [ ];

  boot = {
    loader = {
      systemd-boot.enable = true;
      timeout = null;
    };

    supportedFilesystems = [ "zfs" ];

    initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
    initrd.luks.devices."nixroot".device = "/dev/disk/by-uuid/${poolUUID}";
  };

  # high-resolution display
  # hardware.video.hidpi.enable = lib.mkDefault true;
}
